In [1]:
import yfinance

Stock_Symbol = "AMD"
Start_Date = "2020-01-01"
End_Date = "2025-01-01"

dataframe = yfinance.download(tickers = Stock_Symbol,
                             start = Start_Date,
                             end = End_Date)

dataframe

[*********************100%***********************]  1 of 1 completed


Price,Close,High,Low,Open,Volume
Ticker,AMD,AMD,AMD,AMD,AMD
Date,,,,,
2020-01-02,49.099998,49.250000,46.630001,46.860001,80331100
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000
...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200


In [2]:
dataframe["Returns"] = dataframe["Close"].pct_change()

dataframe

Price,Close,High,Low,Open,Volume,Returns
Ticker,AMD,AMD,AMD,AMD,AMD,
Date,,,,,,
2020-01-02,49.099998,49.250000,46.630001,46.860001,80331100,NaN
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705
...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740


In [3]:
dataframe = dataframe.dropna()

In [4]:
dataframe

Price,Close,High,Low,Open,Volume,Returns
Ticker,AMD,AMD,AMD,AMD,AMD,
Date,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834
...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740


In [6]:
import numpy as np

Buy = 1
Sell = 0

dataframe["Buy/Sell on Open"] = np.where(dataframe["Open"].shift(-1) > dataframe["Open"],
                                       Buy,
                                       Sell)
dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_108336\357502640.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Buy/Sell on Open"] = np.where(dataframe["Open"].shift(-1) > dataframe["Open"],


Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open
Ticker,AMD,AMD,AMD,AMD,AMD,,
Date,,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183,0
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321,1
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893,0
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705,1
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834,1
...,...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563,0
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740,0


In [8]:
dataframe["Buy/Sell on Close"] = np.where(dataframe["Close"].shift(-1) > dataframe["Close"],
                                       Buy,
                                       Sell)
dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_108336\133397674.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Buy/Sell on Close"] = np.where(dataframe["Close"].shift(-1) > dataframe["Close"],


Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open,Buy/Sell on Close
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183,0,0
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321,1,0
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893,0,0
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705,1,1
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834,1,0
...,...,...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563,0,0
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740,0,1


In [9]:
Decreased = 1
Increased = 0

dataframe["Volume Increase/Decrease"] = np.where(dataframe["Volume"].shift(-1) > dataframe["Volume"],
                                                Decreased,
                                                Increased)
dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_108336\3964527213.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Volume Increase/Decrease"] = np.where(dataframe["Volume"].shift(-1) > dataframe["Volume"],


Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open,Buy/Sell on Close,Volume Increase/Decrease
Ticker,AMD,AMD,AMD,AMD,AMD,,,,
Date,,,,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183,0,0,0
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321,1,0,1
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893,0,0,0
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705,1,1,1
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834,1,0,0
...,...,...,...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563,0,0,1
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740,0,1,1


In [10]:
y = dataframe["Buy/Sell on Close"]

X = dataframe.drop(["Buy/Sell on Close"], axis = 1)

y

Date
2020-01-03    0
2020-01-06    0
2020-01-07    0
2020-01-08    1
2020-01-09    0
             ..
2024-12-24    0
2024-12-26    1
2024-12-27    0
2024-12-30    0
2024-12-31    0
Name: Buy/Sell on Close, Length: 1257, dtype: int32

In [11]:
X

Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open,Volume Increase/Decrease
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183,0,0
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321,1,1
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893,0,0
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705,1,1
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834,1,0
...,...,...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563,0,1
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740,0,1


In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train

Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open,Volume Increase/Decrease
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2024-11-25,141.130005,142.350006,139.050003,140.490005,30923100,0.020094,1,1
2022-05-11,87.919998,93.459999,86.529999,87.839996,136137900,-0.009129,0,0
2023-05-22,108.000000,108.790001,103.489998,104.680000,65424200,0.020601,1,1
2023-12-22,139.600006,140.699997,138.309998,140.479996,35370400,-0.002216,0,1
2020-12-15,97.120003,97.980003,95.449997,95.930000,57232700,0.024689,1,0
...,...,...,...,...,...,...,...,...
2020-10-06,84.480003,87.250000,83.540001,86.209999,52725400,-0.019385,0,0
2021-03-17,82.629997,83.250000,80.410004,81.750000,43320600,-0.001450,0,1


In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler

StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train = scaler.transform(X_train)

X_train

array([[ 1.0463047 ,  1.00054698,  1.06638939, ...,  0.54686784,
         0.96864421,  1.05456513],
       [-0.44436295, -0.34076433, -0.4313759 , ..., -0.33008125,
        -1.0323708 , -0.94825817],
       [ 0.11817427,  0.07981865,  0.05228929, ...,  0.56208448,
         0.96864421,  1.05456513],
       ...,
       [-0.19615181, -0.20550837, -0.21948718, ...,  0.67765401,
         0.96864421,  1.05456513],
       [-0.53036837, -0.51004   , -0.54145538, ..., -0.69985097,
        -1.0323708 ,  1.05456513],
       [ 0.02432474,  0.00272556,  0.06654829, ...,  0.21878294,
         0.96864421,  1.05456513]])

In [16]:
X_test = scaler.transform(X_test)

X_test

array([[ 0.23331511,  0.36514566,  0.28556651, ..., -1.77699043,
        -1.0323708 , -0.94825817],
       [-1.37809614, -1.38906658, -1.35222192, ...,  0.15979941,
        -1.0323708 ,  1.05456513],
       [-0.49759111, -0.49824282, -0.46930489, ..., -0.17081732,
        -1.0323708 , -0.94825817],
       ...,
       [-0.02330055, -0.00385906, -0.14476995, ...,  1.48216304,
         0.96864421, -0.94825817],
       [-0.57239057, -0.6060635 , -0.5480144 , ...,  0.36370262,
        -1.0323708 , -0.94825817],
       [-0.49394905, -0.53774969, -0.5448774 , ...,  1.53970216,
         0.96864421,  1.05456513]])

In [17]:
y_train

Date
2024-11-25    0
2022-05-11    0
2023-05-22    1
2023-12-22    1
2020-12-15    0
             ..
2020-10-06    1
2021-03-17    0
2022-08-01    1
2020-08-07    0
2021-08-20    1
Name: Buy/Sell on Close, Length: 942, dtype: int32

In [19]:
from sklearn.neural_network import MLPClassifier

Side_Length = 12
Maximum_Epochs = 300

neural_network = MLPClassifier(hidden_layer_sizes = (Side_Length, Side_Length, Side_Length), max_iter = Maximum_Epochs)

neural_network.fit(X_train, y_train)

C:\Python\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(12, 12, 12), max_iter=300)

In [20]:
predictions = neural_network.predict(X_test)

predictions

array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,

In [21]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

array([[93, 73],
       [67, 82]], dtype=int64)

In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.58      0.56      0.57       166
           1       0.53      0.55      0.54       149

    accuracy                           0.56       315
   macro avg       0.56      0.56      0.56       315
weighted avg       0.56      0.56      0.56       315



In [33]:
neural_network.coefs_

[array([[-0.37547131, -0.4450053 ,  0.56213882, -0.57517515,  0.18760941,
          0.63798436, -0.13776801,  0.41086077,  0.09221907, -0.55673024,
         -0.20816149, -0.05600149],
        [-0.42212322,  0.5735774 ,  0.32705352, -0.5348596 , -0.736027  ,
          0.01994211,  0.18129048, -0.36109276,  0.15458111, -0.38120078,
          0.25580243,  0.0225527 ],
        [ 0.18976304, -0.23078364,  0.40845788, -0.61167898, -0.37748023,
          0.46162914,  0.27578221, -0.036787  , -0.15958665,  0.04798705,
         -0.22162979,  0.47354094],
        [-0.43689759,  0.4006624 , -0.39396953, -0.15588933, -0.14924743,
          0.03173771, -0.40131777, -0.0895062 ,  0.0622693 ,  0.39959997,
         -0.37742674,  0.17752126],
        [-0.35611109, -0.04925833,  0.70347152, -0.03845588,  0.5098466 ,
         -0.35025356, -0.19850274, -0.29427324, -0.40890881,  0.02125328,
          0.75799905,  0.59035235],
        [-0.56522666, -0.48330261,  0.23663637, -0.10169262,  0.36541262,
      

In [34]:
neural_network.intercepts_

[array([-0.28874495, -0.2686836 ,  0.17124975,  0.4992655 ,  0.10943685,
         0.65297901, -0.13876812,  0.05844834, -0.05266537,  0.47188913,
         0.27885386,  0.04549476]),
 array([ 0.29761037,  0.05660085, -0.03161364,  0.51010009, -0.34962641,
        -0.19632878, -0.275653  ,  0.30038594, -0.2540622 , -0.16806232,
         0.35739574,  0.06234141]),
 array([ 0.39141404, -0.18460807,  0.44261418,  0.41562306,  0.28991877,
         0.19219797,  0.08139689, -0.19458793, -0.03894679,  0.25598742,
        -0.23320684, -0.00607207]),
 array([-0.12683605])]